Feature/silent mode (#2)
* obscre file process

* debug launch added

* output filename for enc/dec

* obscure functionality

* obscure file functionality

* test script for obscure_lib.sh

* extra logs added

* extra space added

* startup script added

* changes to the path

* changes

* obscure operation udated

* fq path added.

* remove/create folders

* silent mode changes added

* ext removed, validation added

* efc file name change

* relese 2.0.0

Co-authored-by: cellmate <cellmate@protonemail.com>

diff --git a/efc b/efc
--- a/efc
+++ b/efc
@@ -18,30 +18,67 @@ dependencies_loaded=0
 load_dependencies() {
     # check dependencies exists in current folder, yes -> set variable, no -> read from env. location
     source_path=$(pwd)
-    lib_location="$source_path/efc_lib.sh"
+    lib_location="$source_path/efc_lib"
 
     if [ ! -f "$lib_location" ]; then
 
         # check for the folder path in bash profile
         if [ -z "$EFC_PATH" ]; then
             echo "WARNING: missing the environmen variable EFC_PATH on local bash profile."
-        elif [ ! -f "$EFC_PATH/efc_lib.sh" ]; then
+        elif [ ! -f "$EFC_PATH/efc_lib" ]; then
             echo "WARNING: invalid source is provided in the EFC_PATH. It should be the source location."
         else
             echo "INFO: reading the EFC_PATH from local bash profile : $EFC_PATH"
-            source "$EFC_PATH/efc_lib.sh"
+            source "$EFC_PATH/efc_lib"
             dependencies_loaded=1
         fi
     else
         # setting the EFC_PATH location to execution folder
         export EFC_PATH="$source_path"
         echo "INFO: setting the EFC_PATH to current location : $EFC_PATH"
-        source "$EFC_PATH/efc_lib.sh"
+        source "$EFC_PATH/efc_lib"
         dependencies_loaded=1
     fi
 }
 
 ts=$(date +%s)
+
+read_password_file() {
+    password=$(head -n 1 $1)
+
+    if [ -z "$password" ]; then
+        echo "[error] password can not be empty! make sure password file is accessible and not empty."
+        exit
+    fi
+
+}
+
+accept_task_flag() {
+    if [[ $1 = "e" ]]; then
+        isEnrypt='e'
+    elif [[ $1 = "d" ]]; then
+        isEnrypt='d'
+    else
+        echo "[error] invalid task! should be e = for encrypt , d = for decrypt"
+        exit
+    fi
+}
+
+accept_zip_falg() {
+    if [[ $1 = "yes" ]]; then
+        zipFolders='yes'
+    else
+        zipFolders='no'
+    fi
+}
+
+accept_delete_falg() {
+    if [[ $1 = "yes" ]]; then
+        isDelete='yes'
+    else
+        isDelete='no'
+    fi
+}
 
 user_input() {
 
@@ -141,9 +178,7 @@ process_all_files_in_dir() {
                     ((counter++))
                 fi
             fi
-
         done
-
 }
 
 process_file() {
@@ -158,8 +193,6 @@ process_file() {
 
 }
 
-
-
 zip_folder() {
     if [ "$zipFolders" == 'yes' ]; then
         echo "Start archiving process..."
@@ -167,27 +200,52 @@ zip_folder() {
     fi
 }
 
+print_help() {
+
+    echo -e "\nUsage: efc [FILE/FOLDER] [OPTIONS...] :
+
+Examples:
+\t efc /data/to_encrypt \t# will prompt the user intractive mode.
+\t efc -s /data/to_encrypt -t e -p password.txt -d yes -z no \t# will perfom the encryption task on the given folder.
+
+Intractive mode:
+\t efc [FILE/FOLDER] \t provide the folder path or file directly without other parameters.
+
+Silent mode:
+\t -s | source | source file/folder to encrypt/decrypt.
+\t -o | output | output file name or folder location.
+\t -t | task | task to perform either encrypt or decrypt.
+\t -p | password_file | file containing the password (1st line will be read).
+\t -d | delete_source | once the task is completed: yes, to delete the source file.
+\t -z | zip_sub_folders | when encrypting yes to zip, the subfolders before that task no to avoid compressing."
+}
+
 start_process() {
     if [ $# -eq 0 ]; then
         echo "No folder/file provided, exiting."
         exit 1
-
     elif [[ "$1" == '--version' ]]; then
         print_version_info
         exit 1
-    elif [[ -d "$1" ]]; then
-        echo "Using the directory : $1"
-        user_input "$1"
-        echo -e "\n"
-        zip_folder "$1"
-        echo -e "\n"
-        process_all_files_in_dir "$1"
-    elif [[ -f $1 ]]; then
-        echo "Using the file : $1"
-        user_input $1
-        process_file "$1"
+    elif [[ "$1" == '--help' ]]; then
+        print_help
+        exit 1
     else
-        echo -e '\n' "invalid input, must be a folder or a file : $1"
+
+        if [[ -d "$1" ]]; then
+            echo "Using the directory : $1"
+            user_input "$1"
+            echo -e "\n"
+            zip_folder "$1"
+            echo -e "\n"
+            process_all_files_in_dir "$1"
+        elif [[ -f $1 ]]; then
+            echo "Using the file : $1"
+            user_input $1
+            process_file "$1"
+        else
+            echo -e '\n' "invalid input, must be a folder or a file : $1"
+        fi
     fi
 }
 
@@ -198,4 +256,42 @@ if [ $dependencies_loaded -eq 0 ]; then
     load_dependencies
 fi
 
-start_process "$1"
+if [[ $# -gt 1 ]]; then
+
+    while getopts s:o:t:p:d:z: opts; do
+        case ${opts} in
+        s) source="${OPTARG}" ;;
+        o) output="${OPTARG}" ;;
+        t) operation="${OPTARG}" ;;
+        p) password_file="${OPTARG}" ;;
+        d) delete_source="${OPTARG}" ;;
+        z) zip_sub_folders="${OPTARG}" ;;
+        *)
+            echo -e "[error] invalid parameter, \ntry -help for more information"
+            exit
+            ;;
+        esac
+    done
+
+    # TODO: implement destination file name change
+    echo "$output"
+
+    accept_task_flag "$operation"
+    read_password_file "$password_file"
+    accept_delete_falg "$delete_source"
+    accept_zip_falg "$zip_sub_folders"
+
+    if [[ -d "$source" ]]; then
+        echo "Using the directory : $source"
+        zip_folder "$source"
+        process_all_files_in_dir "$source"
+    elif [[ -f "$source" ]]; then
+        echo "Using the file : $source"
+        process_file "$source"
+    else
+        echo -e '\n' "invalid source, must be a folder or a file : $source"
+    fi
+
+else
+    start_process "$1"
+fi
